---
deployment:
  tasks:
    - npm install
    - npm run build
    - npm run export
  destination:
    - /home/dsajbbvh/public_html/
  exclude:
    - node_modules/
    - .next/
    - package.json
    - package-lock.json
  cleanup:
    - out/
